---
- hosts: default
  remote_user: miguel
  sudo: yes
  vars:
   TOKENMOTOGP: "{{ lookup('env','TOKENMOTOGP') }}"
   DATABASE_URL: "{{ lookup('env','DATABASE_URL')}}"
  tasks:
  - name: Update
    command: apt-get update
  - name: essential
    command: apt-get install -y build-essential
  - name: Install git
    command: apt-get install -y git
  - name: Instalar pip
    apt: name=python-pip state=present
  - name: Instalar paquetes necesarios
    apt: name=python-setuptools state=present
    apt: name=python-dev state=present
    apt: name=libgdbm-dev state=present
    apt: name=libncurses5-dev state=present
    apt: name=postgresql state=present
    apt: name=postgresql-contrib state=present
    apt: name=libpq-dev state=present
  - name: Instalar supervisor
    apt: name=supervisor state=latest
  - name: Configurar supervisor
    template: src=bot_motoGP.conf dest=/etc/supervisor/conf.d/bot_motoGP.conf
  - name: Clone
    shell: rm -rf IV && git clone https://github.com/Miguelmoral/IV
  - name: Actualizar pip
    command: pip install -y -U pip
    command: sudo apt-get install -y python-dev
  - name: Instalar requirements
    command: sudo pip install -r IV/requirements.txt
  - name: Ejecutar supervisor
    service: name=supervisor state=started
